### ISSUE TITLE
Ignore 'watched' folder

### ISSUE THREAD

**Issue by tty-tourist** [iCHAIT/moviemon#4]
It would be great if you could define the paths to your 'watched' and 'unwatched' folders independently, and then use a flag if you wish to ignore the content of the watched folder.

**Comment by iCHAIT** [comment]
Hi @tty-tourist , firstly sorry for not getting back to you sooner and thanks for your suggestion.

The way I have my directory structure for movies setup is that I have 2 separate folders:
- **watched** - that contains all the movies I have already watched.
- **unwatched** - contains all the movies that I have not watched

So I run `moviemon` on the `unwatched` folder only thereby indexing all the movies that I haven't watched yet. 

The problem with having this feature is that every user has his directory structure uniquely defined, for instance, some users name their watched folders as `Seen` and unwatched as `Unseen` or some don't even have such segregation at all. It all depends on the users preference. So it would be a tricky thing to monitor using code, I believe it is better off to run it depending on your folder.

Thoughts?
